"""Expected schemas and column classifications."""

from __future__ import annotations

RESEARCH_COLUMNS: list[str] = [
    "Timestamp",
    "UTC Timestamp",
    "Broker Timestamp",
    "Symbol",
    "Timeframe",
    "Asset Class",
    "Session",
    "Day of Week",
    "Hour UTC",
    "Open",
    "High",
    "Low",
    "Close",
    "Tick Volume",
    "Real Volume",
    "Spread",
    "Direction",
    "Body Size",
    "Range Size",
    "Upper Wick",
    "Lower Wick",
    "Body-to-Range Ratio",
    "Upper Wick Ratio",
    "Lower Wick Ratio",
    "Average Body 5",
    "Average Body 10",
    "Average Body 20",
    "Current Body Ratio",
    "ATR14",
    "Range-to-ATR",
    "Previous Direction 1",
    "Previous Direction 2",
    "Previous Direction 3",
    "Previous Direction 4",
    "Previous Direction 5",
    "Previous Body Ratio 1",
    "Previous Body Ratio 2",
    "Previous Body Ratio 3",
    "Previous Body Ratio 4",
    "Previous Body Ratio 5",
    "Consecutive Bullish",
    "Consecutive Bearish",
    "Body Expansion",
    "Range Expansion",
    "Swing High",
    "Swing Low",
    "HH",
    "HL",
    "LH",
    "LL",
    "Trend Bias",
    "Breakout State",
    "Retest State",
    "Previous Body",
    "Average Body",
    "Previous Body Ratio",
    "Follow Through",
    "Distance Ratio",
    "Body Strength",
]

OUTCOME_COLUMNS: list[str] = [
    "Symbol",
    "Timeframe",
    "Timestamp",
    "Entry Price",
    "Direction",
    "TP Level",
    "SL Level",
    "Forward Horizon Bars",
    "TP SL Model",
    "First Reaction",
    "MFE",
    "MAE",
    "TP Hit",
    "SL Hit",
    "TP Hit Time",
    "SL Hit Time",
    "Outcome",
    "Bars To Outcome",
    "Final Forward Return",
    "Forward Bars Available",
    "Enrichment Status",
]

JOIN_KEYS = ("Symbol", "Timeframe", "Timestamp")

RESEARCH_NUMERIC_COLUMNS = [
    "Hour UTC",
    "Open",
    "High",
    "Low",
    "Close",
    "Tick Volume",
    "Real Volume",
    "Spread",
    "Direction",
    "Body Size",
    "Range Size",
    "Upper Wick",
    "Lower Wick",
    "Body-to-Range Ratio",
    "Upper Wick Ratio",
    "Lower Wick Ratio",
    "Average Body 5",
    "Average Body 10",
    "Average Body 20",
    "Current Body Ratio",
    "ATR14",
    "Range-to-ATR",
    "Previous Direction 1",
    "Previous Direction 2",
    "Previous Direction 3",
    "Previous Direction 4",
    "Previous Direction 5",
    "Previous Body Ratio 1",
    "Previous Body Ratio 2",
    "Previous Body Ratio 3",
    "Previous Body Ratio 4",
    "Previous Body Ratio 5",
    "Consecutive Bullish",
    "Consecutive Bearish",
    "Body Expansion",
    "Range Expansion",
    "Swing High",
    "Swing Low",
    "HH",
    "HL",
    "LH",
    "LL",
    "Trend Bias",
    "Breakout State",
    "Retest State",
    "Previous Body",
    "Average Body",
    "Previous Body Ratio",
    "Follow Through",
    "Distance Ratio",
    "Body Strength",
]

OUTCOME_NUMERIC_COLUMNS = [
    "Entry Price",
    "Direction",
    "TP Level",
    "SL Level",
    "Forward Horizon Bars",
    "First Reaction",
    "MFE",
    "MAE",
    "TP Hit",
    "SL Hit",
    "Bars To Outcome",
    "Final Forward Return",
    "Forward Bars Available",
]

OUTCOME_ONLY_COLUMNS = [
    "Entry Price",
    "TP Level",
    "SL Level",
    "Forward Horizon Bars",
    "TP SL Model",
    "First Reaction",
    "MFE",
    "MAE",
    "TP Hit",
    "SL Hit",
    "TP Hit Time",
    "SL Hit Time",
    "Outcome",
    "Bars To Outcome",
    "Final Forward Return",
    "Forward Bars Available",
    "Enrichment Status",
]

OUTCOME_LEAKAGE_COLUMNS = set(OUTCOME_ONLY_COLUMNS)

RESEARCH_IDENTITY_COLUMNS = [
    "Timestamp",
    "UTC Timestamp",
    "Broker Timestamp",
    "Symbol",
    "Timeframe",
    "Asset Class",
    "Session",
    "Day of Week",
]

RECOMMENDED_FEATURE_COLUMNS = [
    c
    for c in RESEARCH_COLUMNS
    if c not in RESEARCH_IDENTITY_COLUMNS
    and c not in {"Open", "High", "Low", "Close", "Tick Volume", "Real Volume", "Spread"}
]

EXCLUDE_FROM_TRAINING = list(RESEARCH_IDENTITY_COLUMNS) + [
    "Open",
    "High",
    "Low",
    "Close",
    "Tick Volume",
    "Real Volume",
    "Spread",
] + OUTCOME_ONLY_COLUMNS

SUGGESTED_TARGETS = [
    "Outcome",
    "TP Hit",
    "SL Hit",
    "First Reaction",
    "Final Forward Return",
    "MFE",
    "MAE",
]
